//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebVideoPortal.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Questionaires = new HashSet<Questionaire>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string PasswordHash { get; set; }
        public bool EmailConfirmed { get; set; }
        public System.Guid UID { get; set; }
        public bool FirstLogin { get; set; }
        public string CompanyName { get; set; }
    
        public virtual ICollection<Questionaire> Questionaires { get; set; }
    }
}
